-- 01_schema.sql
-- Optimized for 1.5M Records (Oracle 23ai Free)

SET SERVEROUTPUT ON;
PROMPT '📦 Initializing Standard Enterprise Schema...';

-- Cleanup
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_REVIEWS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 1. Products Table
CREATE TABLE PRODUCTS (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asin VARCHAR2(50) UNIQUE,
    title VARCHAR2(4000),
    image_url VARCHAR2(1000)
);

-- 2. Reviews Table
CREATE TABLE CUSTOMER_REVIEWS (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    review_text CLOB,
    review_rating NUMBER(1),
    vector_content VECTOR(1024, *, DENSE),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) LOB (review_text) STORE AS SECUREFILE (
    COMPRESS HIGH
    CACHE
);

-- 3. Indexes
CREATE INDEX idx_products_asin ON PRODUCTS(asin);
CREATE INDEX idx_reviews_rating ON CUSTOMER_REVIEWS(review_rating);

PROMPT '✅ Schema Ready.';
