-- 01_schema.sql
-- Relational, JSON, and Unstructured Data Schema

-- 1. Relational Tables (Sales & Inventory)
CREATE TABLE PRODUCTS (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100),
    price NUMBER(10, 2),
    old_price NUMBER(10, 2),
    stock_quantity NUMBER,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SALES (
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    sale_date DATE DEFAULT SYSDATE,
    quantity NUMBER,
    amount NUMBER(12, 2)
);

-- 2. Document (JSON) Table
CREATE TABLE PRODUCT_SPECS (
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    specs_json JSON,
    CONSTRAINT product_specs_pk PRIMARY KEY (product_id)
);

-- 3. Unstructured/Vector Table
CREATE TABLE CUSTOMER_REVIEWS (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    customer_name VARCHAR2(100),
    review_text CLOB,
    review_rating NUMBER(1),
    review_vector VECTOR(4096, *), -- Llama 3 embedding dimension is often 4096 or similar, adjusted for 23ai
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Core Indexes
CREATE INDEX idx_products_price ON PRODUCTS(price);
CREATE INDEX idx_products_cat ON PRODUCTS(category);
