-- 01_schema.sql
-- Professional Enterprise Schema for 80GB Amazon Dataset
-- Optimized for 32GB RAM & 145M Records (Oracle 23ai)

SET SERVEROUTPUT ON;

PROMPT '📦 Initializing Enterprise Database Schema (High-Performance Mode)...';

-- Cleanup
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_REVIEWS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCT_SPECS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SALES CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 1. Relational Tables (Sales & Inventory)
CREATE TABLE PRODUCTS (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(4000),
    category VARCHAR2(1000),
    price NUMBER(10, 2),
    old_price NUMBER(10, 2),
    stock_quantity NUMBER,
    asin VARCHAR2(50)
) TABLESPACE USERS;

-- 2. Document (JSON) Table - Optimized for Massive Spec Blocks
CREATE TABLE PRODUCT_SPECS (
    spec_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    specs_json CLOB,
    CONSTRAINT specs_json_is_json CHECK (specs_json IS JSON)
) LOB (specs_json) STORE AS SECUREFILE (
    TABLESPACE USERS
    COMPRESS HIGH
    CACHE
);

-- 3. Unstructured/Vector Table - Optimized for semantic search
CREATE TABLE CUSTOMER_REVIEWS (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES PRODUCTS(product_id),
    customer_name VARCHAR2(255),
    review_text CLOB,
    review_rating NUMBER(1),
    review_vector VECTOR(1024, *, DENSE),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) LOB (review_text) STORE AS SECUREFILE (
    TABLESPACE USERS
    COMPRESS HIGH
    CACHE
) TABLESPACE USERS;

-- 4. High-Performance Indexing
CREATE INDEX idx_products_price ON PRODUCTS(price) TABLESPACE USERS;
CREATE INDEX idx_products_cat ON PRODUCTS(category) TABLESPACE USERS;
CREATE INDEX idx_reviews_rating ON CUSTOMER_REVIEWS(review_rating) TABLESPACE USERS;

PROMPT '✅ Enterprise Schema Ready for 145M Records.';
