-- 04_external_tables.sql
-- High-Speed Data Loading via Oracle External Tables (Organized Enterprise Version)

-- 1. Create a logical directory inside Oracle mapping to the 'ingest' subfolder
-- Volume mount: ./data:/opt/oracle/data_in
-- Ingest files at: ./data/ingest/ -> /opt/oracle/data_in/ingest/
CREATE OR REPLACE DIRECTORY INGEST_DIR AS '/opt/oracle/data_in/ingest';
GRANT READ, WRITE ON DIRECTORY INGEST_DIR TO DEMO_USER;

-- 2. Define External Tables for Each Category
-- Electronics
CREATE TABLE EXT_PRODUCTS_ELECTRONICS (asin VARCHAR2(50), name VARCHAR2(1000), brand VARCHAR2(255), category VARCHAR2(255), price NUMBER, specs_json CLOB)
ORGANIZATION EXTERNAL (TYPE ORACLE_LOADER DEFAULT DIRECTORY INGEST_DIR ACCESS PARAMETERS 
(RECORDS DELIMITED BY NEWLINE SKIP 1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL) LOCATION ('processed_metadata_electronics.csv')) REJECT LIMIT UNLIMITED;

-- Home & Kitchen
CREATE TABLE EXT_PRODUCTS_HOME (asin VARCHAR2(50), name VARCHAR2(1000), brand VARCHAR2(255), category VARCHAR2(255), price NUMBER, specs_json CLOB)
ORGANIZATION EXTERNAL (TYPE ORACLE_LOADER DEFAULT DIRECTORY INGEST_DIR ACCESS PARAMETERS 
(RECORDS DELIMITED BY NEWLINE SKIP 1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL) LOCATION ('processed_metadata_home_and_kitchen.csv')) REJECT LIMIT UNLIMITED;

-- Tools
CREATE TABLE EXT_PRODUCTS_TOOLS (asin VARCHAR2(50), name VARCHAR2(1000), brand VARCHAR2(255), category VARCHAR2(255), price NUMBER, specs_json CLOB)
ORGANIZATION EXTERNAL (TYPE ORACLE_LOADER DEFAULT DIRECTORY INGEST_DIR ACCESS PARAMETERS 
(RECORDS DELIMITED BY NEWLINE SKIP 1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL) LOCATION ('processed_metadata_tools.csv')) REJECT LIMIT UNLIMITED;

-- 3. Define External Table for Combined Reviews
CREATE TABLE EXT_REVIEWS_COMBINED (asin VARCHAR2(50), customer_name VARCHAR2(255), rating NUMBER, review_text CLOB)
ORGANIZATION EXTERNAL (TYPE ORACLE_LOADER DEFAULT DIRECTORY INGEST_DIR ACCESS PARAMETERS 
(RECORDS DELIMITED BY NEWLINE SKIP 1 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' MISSING FIELD VALUES ARE NULL) 
LOCATION (
  'processed_reviews_electronics.csv', 
  'processed_reviews_home_and_kitchen.csv', 
  'processed_reviews_tools.csv'
)) REJECT LIMIT UNLIMITED;

COMMIT;
